export { default as Header } from './layout/Header'
export { default as Footer } from './layout/Footer'
export { default as Thumbnail } from './thumbnail/Thumbnail'
export { default as ThumbnailSwiper } from './thumbnail/ThumbnailSwiper'
export { default as Player } from './remotion/Player'